### ISSUE TITLE
S3 Access issue

### ISSUE THREAD

**Issue by sirmattx** [aws-ia/cfn-ps-inductive-automation-ignition#31]
## Issue 
When deploying the [standalone solution](https://fwd.aws/jNAg7?), I'm experiencing the following issue:
"S3 error: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html"

## Resolution
I identified that the logic in the intrinsic function was incorrect therefore I changed the following code snippet: 
```
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/cfn-ps-aws-vpc/templates/aws-vpc.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
```

to the be
```
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL:
        !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/cfn-ps-aws-vpc/templates/aws-vpc.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Ref QSS3BucketName, !Sub '${QSS3BucketName}-${AWS::Region}']
```

for all the Nested Stack TemplateUrl properties which resolved the issue. However there are other nested stacks that are stored in S3 already with the same issue. Can someone test to confirm if the same issue is experienced and maybe a change can be made on all the templates.
